esphome:
  name: veden-kulutus
  platform: ESP8266
  board: d1_mini
  includes:
    - WaterMeter.h

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
sensor:
- platform: custom
  lambda: |-
    auto watermeter = new WaterMeterComponent();
    App.register_component(watermeter);
    return {watermeter->flow_sensor, watermeter->volume_sensor, watermeter->duration_sensor};

  sensors:
  - name: "Hetkellinen kulutus"
    unit_of_measurement: l/min
    accuracy_decimals: 2
  - name: "Tilavuus"
    unit_of_measurement: l
    accuracy_decimals: 1
  - name: "Aika"
    unit_of_measurement: s
    accuracy_decimals: 0