esphome:
  name: vesivuoto
  platform: ESP8266
  board: d1_mini
  includes:
    - WaterLeak.h

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
sensor:
- platform: custom
  lambda: |-
    auto waterleak = new WaterLeakComponent();
    App.register_component(waterleak);
    return {waterleak->deviation_sensor, waterleak->tripped_sensor};

  sensors:
  - name: "Kosteustaso"
    unit_of_measurement: "%"
    accuracy_decimals: 0
  - name: "Vesivuoto"
    accuracy_decimals: 0
